### ISSUE TITLE
address already in use error on port 8090 && Error: No default engine was specified and no extension was provided

### ISSUE THREAD

**Issue by roncking** [orlenyslp/Caterpillar#12]
Trying to run v2.1 on windows

1. started mongodb  it's listening on port 27017
2. started ganachedli  it's listening on port 8545

When I run gulp, I get the error(s) below it says address already in user :::8090

C:\Caterpillar\v2.1\prototype\caterpillar-core>gulp
[13:04:16] Using gulpfile C:\Caterpillar\v2.1\prototype\caterpillar-core\gulpfile.js
[13:04:16] Starting 'nodemon'...
[13:04:16] Starting 'watch'...
[13:04:17] Finished 'watch' after 159 ms
[13:04:17] Finished 'nodemon' after 1.03 s
[13:04:17] Starting 'browser-sync'...
[13:04:17] Finished 'browser-sync' after 619 ms
[13:04:17] Starting 'default'...
[13:04:17] Finished 'default' after 41 μs
[13:04:17] [nodemon] 1.19.1
[13:04:17] [nodemon] to restart at any time, enter `rs`
[13:04:17] [nodemon] watching: out/**/*.js
[13:04:17] [nodemon] starting `node out/www.js`
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8090
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at new WebSocketServer (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\ws\lib\websocket-server.js:70:20)
    at Object.<anonymous> (C:\Caterpillar\v2.1\prototype\caterpillar-core\out\models\models.controller.js:29:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Caterpillar\v2.1\prototype\caterpillar-core\out\app.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Emitted 'error' event at:
    at Server.emit (events.js:198:13)
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[13:04:19] [nodemon] app crashed - waiting for file changes before starting...
[Browsersync] Proxying: http://localhost:3000
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:7000
    External: http://192.168.56.1:7000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Watching files...

Error: No default engine was specified and no extension was provided.
   at new View (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\view.js:62:11)
   at Function.render (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\application.js:569:12)
   at ServerResponse.render (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\response.js:961:7)
   at app.use (C:\Caterpillar\v2.1\prototype\caterpillar-core\out\app.js:40:9)
   at Layer.handle_error (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\layer.js:71:5)
   at trim_prefix (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:310:13)
   at C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:271:10)
   at Layer.handle_error (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\layer.js:73:5)
   at trim_prefix (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:310:13)
   at C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\index.js:271:10)
   at app.use (C:\Caterpillar\v2.1\prototype\caterpillar-core\out\app.js:21:5)
   at Layer.handle [as handle_request] (C:\Caterpillar\v2.1\prototype\caterpillar-core\node_modules\express\lib\router\layer.js:95:5)

**Comment by orlenyslp** [comment]
It seems you are facing a conflict with the ports. Please check the port 8090 is not in use by another app. Otherwise, try changing the port in the controller of the caterpillar-core (line 44):
https://github.com/orlenyslp/Caterpillar/blob/master/v2.1/prototype/caterpillar-core/src/models/models.controller.ts
