### ISSUE TITLE
Docker image can't connect to Ethereum node

### ISSUE THREAD

**Issue by kdelwat** [orlenyslp/Caterpillar#3]
When running the Docker image as specified in the README, I get the following error:

```
Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545.
    at Object.InvalidConnection (/usr/caterpillar/services-manager/node_modules/web3/lib/web3/errors.js:28:16)
    at HttpProvider.send (/usr/caterpillar/services-manager/node_modules/web3/lib/web3/httpprovider.js:83:22)
    at RequestManager.send (/usr/caterpillar/services-manager/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as accounts] (/usr/caterpillar/services-manager/node_modules/web3/lib/web3/property.js:107:62)
    at /usr/caterpillar/services-manager/out/models/models.controller.js:79:53
    at Array.forEach (native)
    at /usr/caterpillar/services-manager/out/models/models.controller.js:74:47
    at Map.forEach (native)
    at createOracles (/usr/caterpillar/services-manager/out/models/models.controller.js:73:37)
    at /usr/caterpillar/services-manager/out/models/models.controller.js:102:9
```
I've run `testrpc` in another terminal, but it still isn't working. Not sure if I'm doing something wrong :smile:

**Comment by adityank** [comment]
I am facing the same issue.
