### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by aminabrahem** [orlenyslp/Caterpillar#6]
Hi,
when i run caterpillar-core i get this error:
> Error: No default engine was specified and no extension was provided.
   at new View (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\view.js:62:11)
   at Function.render (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\application.js:569:12)
   at ServerResponse.render (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\response.js:961:7)
   at C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\out\app.js:43:9
   at Layer.handle_error (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\router\layer.js:71:5)
   at trim_prefix (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\router\index.js:310:13)
   at C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\router\index.js:271:10)
   at Layer.handle_error (C:\Users\Lenovo\Caterpillar-master\v1.0\caterpillar-core\node_modules\express\lib\router\layer.js:73:5)

Thanks for your help.

**Comment by dandenisa** [comment]
I am facing the same issue.

**Comment by SanjayMittal** [comment]
I am running caterpillar-core v2.0. Stuck with "name2Ids is not defined error". 
--------------------------------------------------------------------------------------------------------------
DEPLOYING MODEL ...
(node:5912) UnhandledPromiseRejectionWarning: Error: ReferenceError: ejs:308
    306|     if (is(node, 'bpmn:ServiceTask')) { -%>
    307|     // <%= nodeName(node.id) %>
 >> 308|     function <%= nodeName(node.id) %>_callbak (uint reqId<%= concatParameters(name2Ids.get(nodeName[0]), false, true, true) %>) external returns(bool) {
    309|         require(msg.sender == oracleAddresses[<%= flowNodeIndex(node.id) %>]);
    310|         uint index = uint(1) << reqId;
    311|         if(requestedID[<%= nodeRealIndex(node.id) %>] & index == index) {

name2Ids is not defined
    at C:\Data\Projects\Caterpillar-master\v2.0\caterpillar-core\out\models\models.parsers.js:1259:19
    at <anonymous>
(node:5912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

------------------------------------------------------------------------------------------------------------
My further analysis.

Filename: Caterpillar-master\v2.0\caterpillar-core\templates\bpmn2sol.ejs
line number: 308
Variable "name2Ids" is not defined in the file.

Whilst I look in the issue for more details - if there is anything missing from my end. Kindly let me know.

**Comment by MacOS** [comment]
Dear Developers,

thank you for your work.

I'm currently involved in a project from my university where I have to use your software. Unfortunately, my team and I are getting the error from above. At this point, we run out of ideas how to fix this problem by our one. Can please give us a hint?

Thank you in advance!

**Comment by orlenyslp** [comment]
This seems to be a compatibility problem with the libraries used by the engine, or some step skipped on the setup of the application. The causes may vary, so I need more information about the steps performed.

**Comment by Ferandal** [comment]
I used version 2.0
To fix the issue there you have to replace in ./out/app.js on line 30
```
res.render('error', {
```
with 
```
res.json({
```

This way express is not trying to use a view engine.
I bet there is something similar for version1.0

**Comment by ZeshunShi** [comment]
Hi, I followed @Ferandal method to change the res.render to res.json. However, I got another issue {"message":"Not Found","error":{"status":404}}. Do you have any clue for that?

**Comment by nicedinner2** [comment]
Same issue happens to me. Any solution find for now? @ZeshunShi @MacOS

**Comment by Saptarshi-Dey** [comment]
It just doesn't work does it?

**Comment by MacOS** [comment]
Actually, we managed to get it to work. Unfortunately, we did not write it down.

**Comment by lupinheiro** [comment]
> Actually, we managed to get it to work. Unfortunately, we did not write it down.

Can you please try to remember ? i need to use Caterpillar for a University Project and i cannot get past this problem. @MacOS
